name: external app prop

postgres_url: jdbc:postgresql://ip-172-31-26-167.ec2.internal:5432/postgres
postgres_usr: postgres
postgres_psw: superpswd
postgres_driver: org.postgresql.Driver

spring:
  datasource:
    platform: postgres
