spring:
  application:
    name: 'studentsapp'
  config:
    activate:
      on-profile: default

---
spring:
  config:
    activate:
      on-profile: key-vault
  database:
    driverClassName: org.postgresql.Driver
  cloud:
    azure:
      keyvault:
        secret:
          enabled: true
          property-source-enabled: true
