spring:
  application:
    name: 'studentsapp'
  config:
    activate:
      on-profile: default

---
spring:
  config:
    activate:
      on-profile: key-vault
  datasource:
    url: jdbc:postgresql://${POSTGRES-SERVER-NAME}:5432/${STUDENTS-DATABASE-NAME}?sslmode=require
    username: ${POSTGRES-LOGIN-NAME}
    password: ${POSTGRES-LOGIN-PASSWORD}
  cloud:
    azure:
      keyvault:
        secret:
          enabled: true
          property-source-enabled: true
